# Application Configuration for the Chronopolis Repair Service

cron:
  repair: 0 0 * * * *
  fulfillment: 0 0 * * * *

repair:
  stage: /data/chronopolis/backup
  preservation: /data/chronopolis/perservation

ingest:
  endpoint: http://localhost:8000
  username: my-user
  password: my-pass

rsync:
  path: bags/
  stage: /export/outgoing/bags
  server: my-server

ace:
  ims: ims.umiacs.umd.edu
  am: http://localhost:8080/ace-am/

spring.profiles.active: default, rsync
logging.file: /var/log/chronopolis/repair.log
